version: "3.6"
services:
  web:
    environment:
      - DB_HOST=db
      - DB_NAME=desparking
      - DB_USER=root
      - DB_PASSWD=root
      - MAPBOX_TOKEN=pk.eyJ1IjoiaGhlbnJ5NDQzIiwiYSI6ImNtaHZ4bnJzOTAwdWQyanI3Z2o5c2JtZmgifQ.9UujI0W5H9tCBSJaZ9NMwQ
